## traefik.yml

# Docker configuration backend
providers:
  kubernetesIngress:
    ingressClass: "exposed"
    ingressEndpoint:
      hostname: "kube.loc"
  kubernetesCRD: {}
  file:
    filename: "/config/tls.yml"
    watch: false

# API and dashboard configuration
api:
  insecure: true

entryPoints:
  http:
    address: ":8000"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: https
    #       scheme: https
  https:
    address: ":8443"

serversTransport:
  insecureSkipVerify: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    
# log:
#   level: DEBUG