---
- name: images
  debug:
    msg: " {{ item.image }} ->  {{ localregistry }}/{{ item.name}}:{{ item.image.split(':').1 }}"
  loop: "{{ images }}"


- name: pull
  shell: | 
    docker tag {{ item.image }} {{ localregistry }}/{{ item.name}}:{{ item.image.split(':').1 }}
  loop: "{{ images }}"

- name: push container images to registries
  shell: | 
    docker push {{ localregistry }}/{{ item.name}}:{{ item.image.split(':').1 }}
  loop: "{{ images }}"

